### PR TITLE
Add request priority and initiator to the HAR

### PR DESCRIPTION
**Pull request by paulirish**
Prefixed with an underscore as they are custom, nonstandard fields

### CODE REVIEW

**Comment by cyrus-and** [comment]
Thanks, there is an [`_initiator`][1] field already, but it is a child of the entry. I think that initiator and priority are more related to the object itself rather than the request. What do you think?

P.S. Since you're rebasing in any case, do you mind putting the `chmod +x ` in a separate commit?

[1]: https://github.com/cyrus-and/chrome-har-capturer/blob/a62406a5a32bb6a4ef0b5fbcc8e64fd6dba78552/lib/har.js#L143

**Comment by paulirish** [comment]
Hah. Sorry I had missed the initiator completely. That's excellent.

Yes I'll nuke my initiator change and separate the mode change. Cheers

**Comment by paulirish** [comment]
updated.

**Comment by cyrus-and** [comment]
Great, thank you! I moved the `_priority` field outside the `request` object though; I think it makes more sense there, for what concerns the HAR context.

**Comment by paulirish** [comment]
Cool. Works for me!

**Pull request merged**
